// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg8Eo8tv7MkQsbTbn-VY4AwA8bHPMyinc',
    appId: '1:403353607960:web:71bda744de6826a0c1c86d',
    messagingSenderId: '403353607960',
    projectId: 'futurechat',
    authDomain: 'futurechat.firebaseapp.com',
    storageBucket: 'futurechat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD0PgzMXAibTikQHUO5g452Fw742hkVKA',
    appId: '1:403353607960:android:e91dfc2d5b1b3f87c1c86d',
    messagingSenderId: '403353607960',
    projectId: 'futurechat',
    storageBucket: 'futurechat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB81BgUH3JKert5tIqNbijycaO2ttLWZ5c',
    appId: '1:403353607960:ios:53a978e83731198ac1c86d',
    messagingSenderId: '403353607960',
    projectId: 'futurechat',
    storageBucket: 'futurechat.appspot.com',
    androidClientId: '403353607960-i7hl1qj4r9o6f59i823s0o92ter5p6vb.apps.googleusercontent.com',
    iosClientId: '403353607960-57ch62uhg7iaobacnrkblbb43gdc6dda.apps.googleusercontent.com',
    iosBundleId: 'com.metamisr.futureChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB81BgUH3JKert5tIqNbijycaO2ttLWZ5c',
    appId: '1:403353607960:ios:53a978e83731198ac1c86d',
    messagingSenderId: '403353607960',
    projectId: 'futurechat',
    storageBucket: 'futurechat.appspot.com',
    androidClientId: '403353607960-i7hl1qj4r9o6f59i823s0o92ter5p6vb.apps.googleusercontent.com',
    iosClientId: '403353607960-57ch62uhg7iaobacnrkblbb43gdc6dda.apps.googleusercontent.com',
    iosBundleId: 'com.metamisr.futureChat',
  );
}
